apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todoapp-pvc-data
  namespace: todoapp-web-ns
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

