apiVersion: v1
kind: ConfigMap
metadata:
  name: todoapp-configs
  namespace: todoapp-web-ns
data:
  DB_ENGINE: "django.db.backends.mysql"
  DB_NAME: "app_db"
  DB_HOST: "mysql-headless-service.db-ns.svc"
  DB_PORT: "3306"
