apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secrets
  namespace: todoapp-web-ns
type: Opaque
stringData:
  SECRET_KEY: "@e2(yx)X&tgh3_s=0yja-h!dpebxsx^dg47x)-k&kq_3zjf*9e*"
  DB_PASSWORD: "devpassword123"
  DB_USER: "app_user"