apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-pv-data
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 512Mi
  hostPath:
    path: /data/
