name: App CI/CD

on:

  push:
    branches: [ "develop" ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' 
      
      - name: Install dev tools 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./docker/todoapp/requirements.txt
          pip install flake8 black isort pytest

      - name: Lint
        run: |
          flake8 .
          black --check .
          isort --check-only .
          
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:sha-${{ github.sha }} docker/todoapp

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
          vuln-type: 'os,library'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'   # фейлити PR при високих CVE

